add commentary tool (#76)
* add commentary tool

* fix test

* format

* fix prompts

* fix mypy

* fix mypy

* mypy ignore

* add multiple topic commentary

* ignore unused  type ignore - Update pyproject.toml

12:03:26  agent_service/tools/feature_data.py:193: error: Unused "type: ignore" comment  [unused-ignore]

there is some unknown diff between mypy behavior on Mohammad's local vs  David local and Jenkins, 

this error is annoying anyway so hide it.

* revise tool description

* revise tool descriptions

* add author names to tools

* fix too description

* fixed input/ouputs in themes

* fix theme tool description

---------

Co-authored-by: David Grohmann <104018429+davidgrohmann@users.noreply.github.com>